<!-- application/layouts/scripts/_footer.phtml -->
<div class="span-22 prepend-1 last" id="footer">
	<center>
		<p>
			<b><a href="<?php echo $this->url(array('controller' => 'mamage', 'action' => 'index'), 'default', true); ?>"><?php echo X_Env::_('back_to_home')?></a></b> |
			<b><a href="http://code.google.com/p/vlc-shares/"><?php echo X_Env::_('project_home')?></a></b>
			<br />
			<b>vlc-shares <?php echo X_VlcShares::VERSION; ?> - &copy; Ximarx 2010</b>
		</p>
	</center>
	<br />
</div>