<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
	<?php $this->headScript()->prependFile($this->baseUrl("/js/webkit/jquery.toastmessage.js")); ?>
	<?php $this->headScript()->prependFile($this->baseUrl("/js/webkit/flowplayer-3.2.6.min.js")); ?>
	<?php $this->headScript()->prependFile($this->baseUrl("/js/webkit/jquery.ba-bbq.js")); ?>
	<?php $this->headScript()->prependFile($this->baseUrl("/js/webkit/jquery.tmpl.js")); ?>
	<?php $this->headScript()->prependFile($this->baseUrl("/js/jquery-1.4.2.min.js")); ?>
	<?php $this->headScript()->prependFile($this->baseUrl('/js/console.js')); ?>
	<?php $this->headScript()->appendFile($this->baseUrl('/js/webkit/app.js')); ?>
	<?php $this->headScript()->captureStart(Zend_View_Helper_Placeholder_Container_Abstract::PREPEND); ?>
		var baseUrl = "<?php echo $this->baseUrl(); ?>";
		var X_Env = {
			p_webkitrenderer_vlcstreaming : "<?php echo X_Env::_('p_webkitrenderer_vlcstreaming'); ?>",
			p_webkitrenderer_vlcstreaming_desc : "<?php echo X_Env::_('p_webkitrenderer_vlcstreaming_desc'); ?>"
		};
	<?php $this->headScript()->captureEnd(); ?>
	<?php $this->headMeta()->appendHttpEquiv('Content-Type','application/xhtml+xml; charset=utf-8'); ?>
	<?php $this->headMeta()->appendName('viewport','width=device-width; initial-scale=1.0; maximum-scale=1.0; width=100%; minimum-scale=1; user-scalable=no;'); ?>
	<?php $this->headLink()->prependStylesheet($this->baseUrl('/css/webkit/style.css')); ?>
	<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/webkit/jquery.toastmessage.css')); ?>
	<?php echo $this->headTitle(); ?> 
	<?php echo $this->headMeta(); ?> 
	<?php echo $this->headLink(); ?> 	
	<?php echo $this->headStyle(); ?> 
	<?php echo $this->headScript(); ?> 
</head>
<body>
	<header id="app-header">
		<a href="<?php echo $this->url(array('controller' => 'manage'), 'default', true); ?>">
			<img id="app-logo" src="<?php echo $this->baseUrl('/images/logo.png');?>"  />
		</a>
		<!-- 
		<nav id="app-global-menu">
			<ul>
				<li><img src="<?php echo $this->baseUrl('/images/mobile/down.png');?>" /></li>
				<li><img src="<?php echo $this->baseUrl('/images/mobile/down.png');?>" /></li>
				<li><img src="<?php echo $this->baseUrl('/images/mobile/down.png');?>" /></li>
			</ul>
		</nav>
		-->
		<h1 id="app-title"><font color="orange">VLC</font><br />Shares</h1>
		<h2 id="app-current-position">VLC Shares</h2>
	</header>
	<section id="app-breadcrumb">
		<nav>
			<ul id="breadcrumb">
				<li><img src="<?php echo $this->baseUrl('/images/altgui/dashboard.png'); ?>" /></li>
				<!-- 
				<li><a href="#animedb/wfoihwihi">Animedb.tv</a></li>
				<li><a href="#animedb/wfoihwihi">Film</a></li>
				<li><a href="#animedb/wfoihwihiwfewf">H</a></li>
				<li>Harry Potter e i doni della morte</li>
				 -->
			</ul>
		</nav>
	</section>
	<section id="app-content">
	</section>
	
	
	<!-- TEMPLATES -->
	
	<script id="tmplItemPlayable" type="text/x-jquery-tmpl">
		<a href="${href}" class="item playable" id="item_${key}">
			{{if thumbnail && thumbnail.length }}
				<img src="${thumbnail}" />
			{{else}}
				<img src="<?php echo $this->baseUrl('/images/webkit/nothumbs.jpg'); ?>" />
			{{/if}}
			<blockquote>
				<h2>${label}</h2>
				<p>${description}</p>
			</blockquote>
		</a>
	</script>

	<script id="tmplItemBrowsable" type="text/x-jquery-tmpl">
		<a href="${href}" class="item browsable" id="item_${key}">
			{{if thumbnail && thumbnail.length && thumbnail != "<?php echo $this->baseUrl(); ?>" }}
				<img src="${thumbnail}" />
			{{else}}
				{{if icon && icon.length && icon != "<?php echo $this->baseUrl(); ?>" }}
					<img src="${icon}" />
				{{else}}
					<img src="<?php echo $this->baseUrl('/images/webkit/nothumbs.jpg'); ?>" />
				{{/if}}
			{{/if}}
			<blockquote>
				<h2>${label}</h2>
				<p>${description}</p>
			</blockquote>
		</a>	
	</script>

	<script id="tmplItemSpecial" type="text/x-jquery-tmpl">
		<a href="${href}" class="item special" id="special_${key}" {{if customargs}}{{html customargs}}{{/if}}>
			<div class="imagebox">
				<img src="${icon}" />
			</div>
			<blockquote>
				<h2>${label}</h2>
				<p>${description}</p>
			</blockquote>
		</a>	
	</script>

	<script id="tmplItemOption" type="text/x-jquery-tmpl">
		<a href="${href}" class="item option {{if highlight}}highlight{{/if}}" id="option_${key}" {{if onClick}}onClick="{{html onClick}}"{{/if}}>
			<div class="imagebox">
				{{if icon && icon.length && icon != "<?php echo $this->baseUrl(); ?>" }}
					<img src="${icon}" />
				{{/if}}
			</div>
			<blockquote>
				<h2>${label}</h2>
				<p>${description}</p>
			</blockquote>
		</a>	
	</script>

	<script id="tmplItemControl" type="text/x-jquery-tmpl">
		<a href="${href}" class="item control {{if customClass}}${customClass}{{/if}}" onClick="{{if onClick}}{{html onClick}}{{/if}}">
			<div class="imagebox">
				{{if icon && icon.length && icon != "<?php echo $this->baseUrl(); ?>" }}
					<img src="${icon}" />
				{{/if}}
			</div>
			<blockquote>
				<h2>${label}</h2>
				<p>${description}</p>
			</blockquote>
		</a>
	</script>

	<script id="tmplItemControl_SeekBar" type="text/x-jquery-tmpl">
		<a href="${href}" class="item control seekbar">
			<div class="imagebox">
				<input type="range" min="0" max="100" />
			</div>
			<blockquote>
				<h2>${label}</h2>
				<p>${description}</p>
			</blockquote>
		</a>
	</script>


	<script id="tmplModeChooserItemDescriber" type="text/x-jquery-tmpl">
		<article id="modechooser-describer">
			<img src="${thumbnail}" />
			<blockquote>
				<h2>${label}</h2>
				<p>${description}</p>
			</blockquote>
		</article>
	</script>


	<script id="tmplSectionBrowser" type="text/x-jquery-tmpl">
		<section id="browser">
			<section id="browser-browsable" class="browser-container">
				<header>
					<h1><?php echo X_Env::_('p_webkitrenderer_browsable_title'); ?></h1>
				</header>
			</section>
		</section>
	</script>

	<script id="tmplSectionModeChooser" type="text/x-jquery-tmpl">
		<section id="modechooser">
		</section>
	</script>

	<script id="tmplSectionModeChooserMain" type="text/x-jquery-tmpl">
		<section id="modechooser-main">
			<section id="modechooser-specials">
			</section>
			<section id="modechooser-maincolumn" class="modechooser-column">
				<h2><?php echo X_Env::_('p_webkitrenderer_options'); ?></h2>
			</section>
		</section>
	</script>
	
	<script id="tmplSectionModeChooserPreferences" type="text/x-jquery-tmpl">
		<section id="modechooser-preferences">
		</section>
	</script>

	<script id="tmplSectionBallot" type="text/x-jquery-tmpl">
		<section id="ballot-inner">
			<header>
				<h1><?php echo X_Env::_("p_webkitrenderer_ballotchoosetitle"); ?></h1>
			</header>
			<a id="ballot-flash" href="${flash.href}" class="item ballot" style="background-image: url(<?php echo $this->baseUrl('/images/webkit/flashplayer.png'); ?>);">
				<blockquote>
					<h2><?php echo X_Env::_("p_webkitrenderer_ballot_player_flash_h2"); ?></h2>
					<p><?php echo X_Env::_("p_webkitrenderer_ballot_player_flash_p"); ?></p>
				</blockquote>
			</a>
			<a id="ballot-sharetoapp" href="${sharetoapp.href}" class="item ballot" style="background-image: url(<?php echo $this->baseUrl('/images/webkit/sharetoappplayer.png'); ?>);">
				<blockquote>
					<h2><?php echo X_Env::_("p_webkitrenderer_ballot_player_sharetoapp_h2"); ?></h2>
					<p><?php echo X_Env::_("p_webkitrenderer_ballot_player_sharetoapp_p"); ?></p>
				</blockquote>
			</a>
			<a id="ballot-directurl" href="${directurl.href}" class="item ballot" style="background-image: url(<?php echo $this->baseUrl('/images/webkit/directurl.png'); ?>);">
				<blockquote>
					<h2><?php echo X_Env::_("p_webkitrenderer_ballot_player_directurl_h2"); ?></h2>
					<p><?php echo X_Env::_("p_webkitrenderer_ballot_player_directurl_p"); ?></p>
				</blockquote>
			</a>
		</section>
	</script>
	
	<script id="tmplSectionOverlay" type="text/x-jquery-tmpl">
		<section id="screen-overlay">
			<section id="screen-overlay-bg"></section>
			<section id="screen-overlay-inner"></section>
		</section>
	</script>
	
	
	<script id="tmplSectionPlayer" type="text/x-jquery-tmpl">
		<section id="player">
			<a id="player-flash" href="${url}" style="${customStyle}" class="${customClass}" {{if customArgs}}{{html customArgs}}{{/if}}>
			</a>
		</section>
	</script>
	
	<script id="tmplSectionControls" type="text/x-jquery-tmpl">
		<section id="controls">
			<header>
				<h1><?php echo X_Env::_("p_webkitrenderer_controls_title"); ?></h1>
			</header>
		</section>
	</script>
	
	<div id="loading">
		<img src="<?php echo $this->baseUrl('/images/webkit/loading.gif'); ?>" alt="...loading..." />
	</div>
	
</body>
</html>