<!-- application/views/scripts/config/index.phtml -->
<?php

$breadcrumb = $this->guiElements()->menu()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::MENU_BREADCRUMB));
/* @var $breadcrumb X_VlcShares_Elements_Menu */
$this->layout()->breadcrumb = $breadcrumb
	->addLinkRoute(X_Env::_('Dashboard'), 'manage', 'index')
	->addLabel(X_Env::_('configs_title').": ".X_Env::_("p_{$this->key}_conf_title"));

$menu = $this->guiElements()->menu()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::MENU_CONTEXTUAL));
$this->layout()->subNavigator =	$menu
	->addLink(X_Env::_('back'), "javascript:window.history.back(-1);");
	
?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/config/index.js")); ?>
<?php $this->headTitle()->prepend(X_Env::_('configs_title').": ".X_Env::_("p_{$this->key}_conf_title")); ?>

<?php if ( count($this->messages) ) :?>
<div class="span-24 last" id="manage-messages">
	<ul>
		<?php foreach ($this->messages as $i => $message ): ?>
			<?php if ( !is_array($message) ) $message = array('text' => $message, 'type' => 'warning'); ?>
			<li class="<?php echo @$message['type']?>">
				<img src="<?php echo @$this->baseUrl("/images/msg_{$message['type']}.png");?>" alt="<?php echo @$message['type']; ?>" />
				<?php echo $message['text']?>
			</li>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>

<div class="unit" id="configs-container">
	<div class="box">
		<div class="header">
			<span class="title"><?php echo X_Env::_('configs_title'); ?></span>
		</div>
		<div class="content">
			<h2 class="fieldset-header"><?php echo X_Env::_("p_{$this->key}_conf_title"); ?></h2>
			<?php echo $this->form; ?>
		</div>
	</div>
</div>
