<!-- application/views/scripts/youtube/category.phtml -->
<?php
/* @var $form Application_Form_YoutubeCategory */
$form = $this->form; 
?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/youtube/style.css')); ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/youtube/video.js")); ?>
<?php $this->headTitle()->prepend(X_Env::_('p_youtube_title_video')); ?>

<div class="span-24 last" id="back-to-home">
	<div class="span-4 box back">
		<a href="<?php echo $this->url(array('controller' => 'manage', 'action' => 'index'), 'default', true); ?>"><?php echo X_Env::_('back_to_home'); ?></a>
	</div>
	<div class="span-18 box title last">
		<h4><?php echo X_Env::_('p_youtube_title_video'); ?></h4>
	</div>
</div>


<?php if ( count($this->messages) ) :?>
<div class="span-24 last" id="manage-messages">
	<ul>
		<?php foreach ($this->messages as $i => $message ): ?>
			<?php if ( !is_array($message) ) $message = array('text' => $message, 'type' => 'warning'); ?>
			<li class="<?php echo @$message['type']?>">
				<img src="<?php echo @$this->baseUrl("/images/msg_{$message['type']}.png");?>" alt="<?php echo @$message['type']; ?>" />
				<?php echo $message['text']?>
			</li>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>

<div class="quickactionbox">
	<button class="quickbox-delete"><?php echo X_Env::_('p_youtube_video_delete'); ?></button>
</div>

<h2><?php echo X_Env::_('p_youtube_main_title_video'); ?></h2>

<div class="span-23 box last" id="p_youtube_videoform">
	<h3><?php echo X_Env::_('p_youtube_form_videodetails')?></h3>
	<?php if ( $form instanceof Zend_Form ):?>
		<form class="zend_form" action="<?php echo $form->getAction()?>" method="<?php echo $form->getMethod()?>" enctype="<?php echo $form->getEnctype();?>">
			<div class="row">
				<div class="label">
					<label for="label"><?php echo $form->idYoutube->getLabel(); ?></label>
				</div>
				<div class="field"><?php echo $form->idYoutube ?></div>
			</div>
			<div class="row">
				<div class="label">
					<label for="label"><?php echo $form->idCategory->getLabel(); ?></label>
				</div>
				<div class="field"><?php echo $form->idCategory ?></div>
			</div>
			<div class="row">
				<center>
					<?php echo $form->csrf; ?>
					<?php echo $form->submit; ?>
					<?php //echo $form->abort; ?>
					<?php echo X_Env::_('or'); ?> 
					<a href="<?php echo $this->url(array('controller'=>'youtube','action'=>"index"), 'default', true); ?>"><?php echo X_Env::_('abort')?></a>
				</center>
			</div>
		</form>
	<?php else: ?>
		<?php echo $form; ?>
	<?php endif; ?>
</div>
