<!-- application/views/scripts/index/collections.mobile.phtml -->
<?php
/* @var $v_items X_Page_ItemList_PItem */
$v_items = $this->items; 
?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/mobile/collections.js")); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/mobile/collections.css'), 'screen'); ?> 
<?php $this->headTitle()->prepend('Home'); ?>

<div id="wrapper"> 
	<div id="header"> 
		<h1 id="siteTitle"><img src="<?php echo $this->baseUrl('/images/mobile/logomobile.png'); ?>" width="172" height="56" alt="Welcome to USCmobile" /></h1> 
	</div>
	<div class="items"> 
			<?php foreach ($v_items->getItems() as $i => $item): ?>
				<?php /* @var $item X_Page_Item_PItem */ ?>
				<div class="item">
					<?php if ( $item->getIcon() != null ) :?>  
						<img src="<?php echo $this->baseUrl($item->getIcon()); ?>" width="48" height="48" alt="" />
					<?php else: ?> 
						<img src="<?php echo $this->baseUrl('/images/mobile/collections_item.png'); ?>" width="48" height="48" alt="" />
					<?php endif; ?> 
					<h3><a href="<?php echo $item->isUrl() ? $item->getLink() : $this->url($item->getLink(), $item->getRoute(), $item->isReset()) ; ?>"><?php echo $item->getLabel(); ?></a></h3> 
					<p><?php echo $item->getDescription(); ?></p> 
					<a class="button" href="<?php echo $item->isUrl() ? $item->getLink() : $this->url($item->getLink(), $item->getRoute(), $item->isReset()) ; ?>"></a> 
				</div> 	
			<?php endforeach; ?> 
	</div>
	<div id="footer"> 
		<ul> 
			<li><a id="feedback" href="http://code.google.com/p/vlc-shares/"><?php echo X_Env::_('p_mobilerenderer_footerproject')?></a></li> 
			<li><a id="uscHome" href="<?php echo $this->url(array('controller' => 'manage', 'action' => 'index' ), 'default', true);?>"><?php echo X_Env::_('p_mobilerenderer_footermanage'); ?></a></li> 
			<li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'collections' ), 'default', true);?>"><?php echo X_Env::_('p_mobilerenderer_footerindex')?></a></li> 
		</ul> 
	</div>
</div>
