<!-- application/views/scripts/youtube/category.phtml -->
<?php
/* @var $form Application_Form_YoutubeCategory */
$form = $this->form; 
?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/youtube/style.css')); ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/youtube/category.js")); ?>
<?php $this->headTitle()->prepend(X_Env::_('p_youtube_title_category')); ?>
<?php $this->headScript()->captureStart(Zend_View_Helper_Placeholder_Container_Abstract::PREPEND); ?>
	var p_youtube_delete_category_confirm = "<?php echo X_Env::_('p_youtube_delete_category_confirm'); ?>";
<?php $this->headScript()->captureEnd(); ?>


<div class="span-24 last" id="back-to-home">
	<div class="span-4 box back">
		<a href="<?php echo $this->url(array('controller' => 'manage', 'action' => 'index'), 'default', true); ?>"><?php echo X_Env::_('back_to_home'); ?></a>
	</div>
	<div class="span-18 box title last">
		<h4><?php echo X_Env::_('p_youtube_title_category'); ?></h4>
	</div>
</div>


<?php if ( count($this->messages) ) :?>
<div class="span-24 last" id="manage-messages">
	<ul>
		<?php foreach ($this->messages as $i => $message ): ?>
			<?php if ( !is_array($message) ) $message = array('text' => $message, 'type' => 'warning'); ?>
			<li class="<?php echo @$message['type']?>">
				<img src="<?php echo @$this->baseUrl("/images/msg_{$message['type']}.png");?>" alt="<?php echo @$message['type']; ?>" />
				<?php echo $message['text']?>
			</li>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>

<div class="quickactionbox">
	<button class="quickbox-add-video"><?php echo X_Env::_('p_youtube_video_new'); ?></button>
	<button class="quickbox-delete"><?php echo X_Env::_('p_youtube_category_delete'); ?></button>
	<button class="quickbox-back"><?php echo X_Env::_('p_youtube_category_backbutton'); ?></button>
</div>

<h2><?php echo X_Env::_('p_youtube_main_title_category'); ?></h2>

<div class="span-24 last" id="p_youtube_framecontainer"></div>

<div class="span-23 box last" id="p_youtube_categoryform">
	<div id="p_youtube_thumbnailpreview" style="display:none"></div>
	<h3><?php echo X_Env::_('p_youtube_form_categorydetails')?></h3>
	<?php if ( $form instanceof Zend_Form ):?>
		<form class="zend_form" action="<?php echo $form->getAction()?>" method="<?php echo $form->getMethod()?>" enctype="<?php echo $form->getEnctype();?>">
			<div class="row">
				<div class="label">
					<label for="label"><?php echo $form->label->getLabel(); ?></label>
				</div>
				<div class="field"><?php echo $form->label ?></div>
			</div>
			<div class="row">
				<div class="label">
					<label for="thumbselect"><?php echo $form->thumbselect->getLabel(); ?></label>
				</div>
				<div class="field"><?php echo $form->thumbselect ?></div>
			</div>
			<div class="row">
				<div class="label">
					<label for="thumbnail"><?php echo $form->thumbnail->getLabel(); ?></label>
				</div>
				<div class="field"><?php echo $form->thumbnail ?></div>
			</div>
			<div class="row">
				<center>
					<?php echo $form->id; ?>
					<?php echo $form->csrf; ?>
					<?php echo $form->submit; ?>
					<?php //echo $form->abort; ?>
					<?php echo X_Env::_('or'); ?> 
					<a href="<?php echo $this->url(array('controller'=>'youtube','action'=>"index"), 'default', true); ?>"><?php echo X_Env::_('abort')?></a>
				</center>
			</div>
		</form>
	<?php else: ?>
		<?php echo $form; ?>
	<?php endif; ?>
</div>

<div class="span-23 box last" id="p_youtube_videos">
	<h3><?php echo X_Env::_('p_youtube_category_videolist')?></h3>
	<div id="p_youtube_thumbnailpreview_video"></div>
	<?php if (count($this->videos)): ?>
		<?php foreach ($this->videos as $video): ?>
			<?php /* @var $video Application_Model_YoutubeVideo */ ?>
			<div id="idVideo-<?php echo $video->getId(); ?>" class="p_youtube_video">
				<div class="quickactionbox">
					<button class="quickbox-delete-video"><?php echo X_Env::_('p_youtube_video_delete'); ?></button>
				</div>
				<h4 class="label"><?php echo $video->getLabel()?></h4>
				<p class="description"><?php echo $video->getDescription(); ?></p>
				<img class="image" src="<?php echo $video->getThumbnail(); ?>" />
			</div>
		<?php endforeach; ?>
	<?php else: ?>
		<h4 align="center"><?php echo X_Env::_('p_youtube_videos_novideo'); ?></h4>
	<?php endif; ?>
</div>
