<?php $this->layout()->disableLayout(); ?>
<ul class="items">
	<?php $preOption = true; ?>
	<?php foreach ($this->items as $i => $item):?>
		<?php if ( $item['label'] == X_Env::_('_____options_separator_____')) { $preOption = false; continue; }?>
		<?php // skip items that aren't options ?>
		<?php if ( $preOption) { continue; }?>
		<li class="item mode <?php echo ((array_key_exists('highlight', $item) && $item['highlight']) ? 'selected' : ''); ?>">
			<?php if ( array_key_exists('icon', $item) ): ?>
				<img src="<?php echo $this->baseUrl($item['icon']); ?>"	alt="" width="32px" height="32px" />
			<?php endif; ?>
			<p class="title"><a href="<?php echo $item['link']; ?>"><?php echo $item['label']; ?></a></p>
			<?php if ( array_key_exists('desc', $item) ): ?>
				<p class="date"><?php echo $item['desc']; ?></p>
			<?php endif; ?>
			<a href="<?php echo $item['link']; ?>" class="button"></a>
			<div class="clear"></div>
		</li>
	<?php endforeach; ?>
</ul>