version=1
background=http://navix.turner3d.net/images/backgrounds/bkg_navix_bh_plain.jpg
logo=http://navix.turner3d.net/images/logos/logo.png
title=Vlc-shares - <?php echo $this->title ?> 
description=<?php echo $this->translate->_("title_description"); ?> 

type=playlist
name=<?php echo $this->translate->_("on_air"); ?> <?php echo $this->now_playing; ?> 
URL=<?php echo $this->thispage; ?> 

type=playlist
name=<?php echo $this->time_now; ?>/<?php echo $this->time_total; ?> 
URL=<?php echo $this->thispage; ?> 


type=video
name=<?php echo $this->resume; ?> 
thumb=<?php echo $this->resume_thumbnail ? $this->resume_thumbnail : 'http://navix.turner3d.net/images/logos/viewed.png'; ?> 
URL=<?php echo $this->resume_url; ?> 

type=playlist
name=<?php echo $this->stop; ?> 
thumb=<?php echo $this->stop_thumbnail ? $this->stop_thumbnail : 'http://navix.turner3d.net/images/logos/viewed.png'; ?> 
URL=<?php echo $this->stop_url; ?> 

type=playlist
name=<?php echo $this->pause; ?> 
thumb=<?php echo $this->pause_thumbnail ? $this->pause_thumbnail : 'http://navix.turner3d.net/images/logos/viewed.png'; ?> 
URL=<?php echo $this->pause_url; ?> 

type=playlist
name=<?php echo $this->fwrd; ?> 
thumb=<?php echo $this->fwrd_thumbnail ? $this->fwrd_thumbnail : 'http://navix.turner3d.net/images/logos/viewed.png'; ?> 
URL=<?php echo $this->fwrd_url; ?> 

type=playlist
name=<?php echo $this->prev; ?> 
thumb=<?php echo $this->prev_thumbnail ? $this->prev_thumbnail : 'http://navix.turner3d.net/images/logos/viewed.png'; ?> 
URL=<?php echo $this->prev_url; ?> 
