<?php

$breadcrumb = $this->guiElements()->menu()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::MENU_BREADCRUMB));
/* @var $breadcrumb X_VlcShares_Elements_Menu */
$this->layout()->breadcrumb = $breadcrumb
	->addLinkRoute(X_Env::_('Dashboard'), 'manage', 'index')
	->addLabel('An error occurred');
	
$menu = $this->guiElements()->menu()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::MENU_CONTEXTUAL));
$this->layout()->subNavigator =	$menu
	->addLink(X_Env::_('back'), "javascript:window.history.back(-1);");

?>

<div class="columns full-height">
	<div class="column">
		<div class="container vertical-center horizontal-center" id="error" style="max-width: 960px;">
			<div class="box">
				<div class="header">
					<span class="title">An error occurred</span>
				</div>
				<div class="content">
					<h3><?php echo $this->message; ?></h3>
					<h2 class="fieldset-header">Error description</h2>
					<p><?php echo $this->exception->getMessage(); ?></p>
					<h2 class="fieldset-header">Request parameters</h2>
					<pre style="overflow: auto;"><?php echo var_export($this->request->getParams(), true) ?></pre>
					<h2 class="fieldset-header">Stack trace</h2>
					<pre style="overflow: auto;"><?php echo $this->exception->getTraceAsString() ?></pre>
				</div>
			</div>
		</div>
	</div>
</div>
