
<div class="columns full-height">
	<div class="column">
		<div class="container vertical-center horizontal-center" id="error">
			<?php /* @var $block X_VlcShares_Elements_Block */ ?>
			<?php $block = $this->guiElements()->block()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::BLOCK_HIGHLIGHT)); ?>
			<?php $block->title->set('An error occurred')->start(); ?>
			<?php $block->header->start(); ?>
				<h3><?php echo $this->message; ?></h3>
			<?php $block->header->end(); ?>
			<?php $block->start(); ?>
				<?php if (isset ($this->exception) ): ?>
					<h2>Error description</h2>
					<?php echo $this->exception->getMessage(); ?>
				<?php endif;?>
				<?php $innerBlock = $this->guiElements()->innerBlock(); ?>
				<?php $innerBlock->title->set('Request parameters'); ?>
				<?php $innerBlock->start(); ?>
					<pre style="overflow: auto;"><?php echo var_export($this->request->getParams(), true) ?></pre>
				<?php echo $innerBlock->end(); ?>
				
				<?php $innerBlock = $this->guiElements()->innerBlock(); ?>
				<?php $innerBlock->title->set('Stack trace'); ?>
				<?php $innerBlock->start(); ?>
					<pre style="overflow: auto;"><?php echo $this->exception->getTraceAsString() ?></pre>
				<?php echo $innerBlock->end(); ?>
			<?php echo $block->end(); ?>
		</div>
	</div>
</div>
