<!-- application/views/scripts/megavideo/index.phtml -->
<?php $this->headScript()->appendFile($this->baseUrl("/js/megavideo/script.js")); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/megavideo/style.css')); ?>
<?php 
$menu = $this->guiElements()->menu()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::MENU_CONTEXTUAL));
$this->layout()->subNavigator =	$menu
	->addLinkRoute(X_Env::_('megavideo_manage_add_new_entry'), "megavideo", "add")
	//->addButton(X_Env::_('megavideo_bookmarklets_title'), "javascript:showModal('bookmarklets'); return false;" )
	->addLinkRoute(X_Env::_('megavideo_manage_options'), "config", "index", array('key' => 'megavideo', 'r' => X_Env::encode('megavideo:index')));
	
$breadcrumb = $this->guiElements()->menu()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::MENU_BREADCRUMB));
/* @var $breadcrumb X_VlcShares_Elements_Menu */
$this->layout()->breadcrumb = $breadcrumb
	->addLinkRoute(X_Env::_('Dashboard'), 'manage', 'index')
	->addLabel(X_Env::_('megavideo_manage_title'));
	
	
$this->headTitle()->prepend(X_Env::_('megavideo_manage_title'));
?>

<?php if ( count($this->messages) ) :?>
<div class="span-24 last" id="manage-messages">
	<ul>
		<?php foreach ($this->messages as $i => $message ): ?>
			<?php if ( !is_array($message) ) $message = array('text' => $message, 'type' => 'warning'); ?>
			<li class="<?php echo @$message['type']?>">
				<img src="<?php echo @$this->baseUrl("/images/msg_{$message['type']}.png");?>" alt="<?php echo @$message['type']; ?>" />
				<?php echo $message['text']?>
			</li>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>


<div class="unit columns on-2">
	<div class="elastic column">
		<div class="container">
			<div class="box">
				<div class="header">
					<span class="title">Libreria Megavideo</span>
					<!-- 
					<ul class="menu">
						<li>
							<a href="#">
								<img src="<?php echo $this->baseUrl('/images/megavideo/logo.png'); ?>" />
							</a>
						</li>
					</ul>
					 -->
				</div>
				<div class="content">
					<table class="table" id="megavideo-categories">
						<tr class="header">
							<th>Categorie</th>
							<th width="100px">Video</th>
							<th width="100px">Opzioni</th>
						</tr>
						<?php foreach ($this->categories as $i => $category): ?>
							<tr class="<?php echo $i % 2 ? 'alt' : ''; ?>">
								<td>
									<a href="<?php echo $this->url(array(
											'controller' => 'megavideo',
											'action'	=> 'category',
											'id'	=> urlencode($category['category'])
										), 'default', true); ?>">
										<?php echo $category['category']; ?>
									</a>
								</td>
								<td><?php echo count($category['entries']);?></td>
								<td>
									<ul class="inline-menu">
										<li class="ui-state-default">
											<a class="ui-icon ui-icon-pencil" href="<?php echo $this->url(array(
												'controller' => 'megavideo',
												'action' => 'rename',
												'id' => urlencode($category['category']),
												'name' => ''
											), 'default', true); ?>">R</a>
										</li>
										<li class="ui-state-default">
											<a class="ui-icon ui-icon-trash" href="<?php echo $this->url(array(
												'controller' => 'megavideo',
												'action' => 'delete',
												'type' => 'category',
												'id' => urlencode($category['category']),
												'name' => ''
											), 'default', true); ?>">E</a>
										</li>
									</ul>
								</td>
							</tr>
						<?php endforeach; ?>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="fixed column" style="width: 400px">
		<div class="container">
			<div class="box" id="megavideo-bookmarklets">
				<div class="header">
					<span class="title">Bookmarklet</span>
				</div>
				<div class="content">
					<center>
						<iframe title="YouTube video player" class="youtube-player" type="text/html" height="260px" src="http://www.youtube.com/embed/GycWEv7cWLk" frameborder="0" allowFullScreen="allowFullScreen"></iframe>
					</center>					
						<br />
					<p align="center">
						<a class="button" id="megavide-bookmarklets-button" href="<?php echo $this->inlineJs; ?>" title="<?php echo X_Env::_('megavideo_bookmarklets_link_title'); ?>">
							 <?php echo X_Env::_('megavideo_bookmarklets_link_title'); ?>
						</a>
					</p>
					<p>
						<?php echo X_Env::_('megavideo_bookmarklets_description')?>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- 
<style>
.field {
 margin: 15px;
 padding: 0.5em;
 border: 1px solid #666;
/* width: 500px;*/
 position: relative;
}
.h2 {
	font:  bold 110% Georgia, serif;	
}
.field h2 {
 display: inline;
 position: absolute;
 top: -15px;
 background: white;
 color: #008;
 margin: 0 3px;

 padding:2px;
 font:  bold 100% Georgia, serif;
}
.field p {
	margin: 0px;
}
.field .controls {
 position: absolute;
 right: 20px;
 top: -13px;
 float: right;
 background: white;
 padding: 2px;
}
.category-manage {
	/*
 position: absolute;
 right: 20px;
 top: -13px;
*/
 /*float: right;*/
}
.separator {
	margin-right: 5px;
	margin-left: 5px;
}

</style>
<script type="text/javascript">
$(document).ready(function(){
	$('div.field').hide();
	$('.category').css('text-decoration','underline');
	$('.category').hover(function(event){
		$(this).css('cursor','pointer');
	}, function(event){
		$(this).css('cursor','auto');
	});
	$('.category').click(function (event) {
		$(this).parent().siblings('div.field').toggle();
	});
	$('.rename').click(function (event){
		event.preventDefault();
		var categoryName = prompt('<?php echo X_Env::_("megavideo_manage_newcategoryname")?>', 'Default');
		if ( categoryName.trim() != "")
			window.location = $(this).attr('href') + escape(categoryName.trim());
	});
});
</script>

-->

<!-- 
<h1><?php echo X_Env::_('megavideo_manage_title');?></h1>
<p>
	<a href="<?php echo $this->url(
    array(
        'controller' => 'index',
        'action'     => 'index'
    ),
    'default',
    true) ?>"><?php echo X_Env::_('megavideo_manage_back_to_index');?></a>
	<span class="separator">|</span>
	<a href="<?php echo $this->url(
	    array(
	        'controller' => 'megavideo',
	        'action'     => 'add'
	    ),
	    'default',
	    true) ?>"><?php echo X_Env::_('megavideo_manage_add_new_entry');?></a>
</p>
<ul>
	<?php foreach ($this->categories as $category): ?>
	<li>
		<div>
			<span class="category h2"><?php echo $category['category']; ?></span>
			<span class="category-manage">
				(
				<a class="rename" href="<?php echo X_Env::routeLink('megavideo', 'rename',
				    array(
				    	'id'			=> urlencode($category['category']),
				    	'name'		=> ''
				    )); ?>				
					"><?php echo X_Env::_('megavideo_manage_category_rename');?></a>
				<span class="separator">|</span>
			    <a href="<?php echo $this->url(
				    array(
				        'controller' => 'megavideo',
				        'action'     => 'delete',
				    	'type'		 => 'category',
				    	'id'			=> $category['category']
				    ),
				    'default',
				    true); ?>"><?php echo X_Env::_('megavideo_manage_category_delete');?></a>
				)
			</span>
		</div>
		<?php foreach ($category['entries'] as $entry ) :?>
			<div class="field">
				<h2><?php echo $entry->getLabel(); ?> - (<?php echo $entry->getIdVideo(); ?>)</h2>
				<div class="controls">
					(
					<a href="<?php echo $this->url(
				    array(
				        'controller'	=> 'megavideo',
				        'action'    	=> 'modify',
				        'id'			=> $entry->getId()
				    ),
				    'default',
				    true) ?>"><?php echo X_Env::_('megavideo_manage_modify');?></a>
				    <span class="separator">|</span>
				    <a href="<?php echo $this->url(
				    array(
				        'controller' => 'megavideo',
				        'action'     => 'delete',
				    	'type'		=>	'video',
				    	'id'			=> $entry->getId()
				    ),
				    'default',
				    true) ?>"><?php echo X_Env::_('megavideo_manage_delete');?></a>
				    )
				</div>
				<p><?php echo $entry->getDescription(); ?></p>
			</div>
		<?php endforeach; ?>
	</li>
	<?php endforeach;?>
</ul>
-->