<!--
<?php /* @var $block X_VlcShares_Elements_Block */ ?>
<?php $block = $this->guiElements()->block(); ?>
<?php $block->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::BLOCK_HIGHLIGHT)); ?>
<?php $block->start(); ?>
	<?php $block->title->set('Titolo'); ?>
	<?php $block->header->start(); ?>
		<h2>this is a wonderfull header text</h2>
	<?php $block->header->end(); ?>
	<div class="fafuffa">
		This is the block body
	</div>
	
	<?php /* @var $innerblock X_VlcShares_Elements_InnerBlock */ ?>
	<?php $innerblock = $this->guiElements()->innerBlock(); ?>
	<?php $innerblock->start(); ?>
		<?php $innerblock->title->set('Titolo interno'); ?>
		Contenuto
	<?php echo $innerblock->end(); ?>
	
	<?php $block->footer->start(); ?>
		<h4>This is the footer</h4>
	<?php $block->footer->end()?>
<?php echo $block->end(); ?>

<?php /* @var $sections X_VlcShares_Elements_SectionContainer */ ?>
<?php $sections = $this->guiElements()->sectionContainer(); ?>
<?php $sections->setSectionsPerRow(3)->setSectionsSameHeight(true); // container options ?>
	<?php for( $i = 0; $i < 10; $i++ ): ?>
		<?php $sections->{"column-$i"}->setSpan($i % 2 ? '2' : '')->start(); ?>
			<?php $block = $this->guiElements()->block()->start(); ?>
				contenuto colonna <?php echo "column-$i"; ?>
			<?php echo $block->end(); ?>
		<?php $sections->{"column-$i"}->end(); ?>
	<?php endfor; ?>
<?php echo $sections; ?>
-->

<?php 
$menu = $this->guiElements()->menu()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::MENU_CONTEXTUAL));
$this->layout()->subNavigator =	$menu
	->addLinkRoute(X_Env::_('megavideo_manage_add_new_entry'), "megavideo", "add")
	->addButton(X_Env::_('megavideo_bookmarklets_title'), "javascript:showModal('bookmarklets'); return false;" )
	->addLinkRoute(X_Env::_('megavideo_manage_options'), "config", "index", array('key' => 'megavideo', 'r' => X_Env::encode('megavideo:index')));
	
$breadcrumb = $this->guiElements()->menu()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::MENU_BREADCRUMB));
/* @var $breadcrumb X_VlcShares_Elements_Menu */
$this->layout()->breadcrumb = $breadcrumb
	->addLinkRoute(X_Env::_('Dashboard'), 'manage', 'index')
	->addLabel(X_Env::_('megavideo_manage_title'));
?>

<style>
.field {
 margin: 15px;
 padding: 0.5em;
 border: 1px solid #666;
/* width: 500px;*/
 position: relative;
}
.h2 {
	font:  bold 110% Georgia, serif;	
}
.field h2 {
 display: inline;
 position: absolute;
 top: -15px;
 background: white;
 color: #008;
 margin: 0 3px;

 padding:2px;
 font:  bold 100% Georgia, serif;
}
.field p {
	margin: 0px;
}
.field .controls {
 position: absolute;
 right: 20px;
 top: -13px;
 float: right;
 background: white;
 padding: 2px;
}
.category-manage {
	/*
 position: absolute;
 right: 20px;
 top: -13px;
*/
 /*float: right;*/
}
.separator {
	margin-right: 5px;
	margin-left: 5px;
}
#bookmarklets {
	position: absolute;
	top: 10px;
	right: 10px;
	z-index: 100;
	width: 250px;
	padding: 5px;
	border: 1px solid black;
	background-color: gray;
	color: white;
}

#bookmarklets-description {
	display: none;
	background-color: white;
	color: black;
	margin: 1px;
	padding: 3px;
}


</style>
<script type="text/javascript">
$(document).ready(function(){
	$('div.field').hide();
	$('.category').css('text-decoration','underline');
	$('.category').hover(function(event){
		$(this).css('cursor','pointer');
	}, function(event){
		$(this).css('cursor','auto');
	});
	$('.category').click(function (event) {
		$(this).parent().siblings('div.field').toggle();
	});
	$('#bookmarklets').hover(function(){
		$('#bookmarklets-description').toggle();
	});
	$('.rename').click(function (event){
		event.preventDefault();
		var categoryName = prompt('<?php echo X_Env::_("megavideo_manage_newcategoryname")?>', 'Default');
		if ( categoryName.trim() != "")
			window.location = $(this).attr('href') + escape(categoryName.trim());
	});
});
</script>



<h1><?php echo X_Env::_('megavideo_manage_title');?></h1>
<p>
	<a href="<?php echo $this->url(
    array(
        'controller' => 'index',
        'action'     => 'index'
    ),
    'default',
    true) ?>"><?php echo X_Env::_('megavideo_manage_back_to_index');?></a>
	<span class="separator">|</span>
	<a href="<?php echo $this->url(
	    array(
	        'controller' => 'megavideo',
	        'action'     => 'add'
	    ),
	    'default',
	    true) ?>"><?php echo X_Env::_('megavideo_manage_add_new_entry');?></a>
</p>
<?php if ($this->bookmarkletsEnabled) : ?>
	<div id="bookmarklets">
		<b><?php echo X_Env::_('megavideo_bookmarklets_title')?></b>
		<div>
			<a href="<?php echo $this->inlineJs; ?>" title="<?php echo X_Env::_('megavideo_bookmarklets_link_title'); ?>">
				 <?php echo X_Env::_('megavideo_bookmarklets_link_title'); ?>
			</a>
		</div>
		<div id="bookmarklets-description">
			<?php echo X_Env::_('megavideo_bookmarklets_description')?>
		</div>
	</div>
<?php endif; ?>
<ul>
	<?php foreach ($this->categories as $category): ?>
	<li>
		<div>
			<span class="category h2"><?php echo $category['category']; ?></span>
			<span class="category-manage">
				(
				<a class="rename" href="<?php echo X_Env::routeLink('megavideo', 'rename',
				    array(
				    	'id'			=> urlencode($category['category']),
				    	'name'		=> ''
				    )); ?>				
					"><?php echo X_Env::_('megavideo_manage_category_rename');?></a>
				<span class="separator">|</span>
			    <a href="<?php echo $this->url(
				    array(
				        'controller' => 'megavideo',
				        'action'     => 'delete',
				    	'type'		 => 'category',
				    	'id'			=> $category['category']
				    ),
				    'default',
				    true); ?>"><?php echo X_Env::_('megavideo_manage_category_delete');?></a>
				)
			</span>
		</div>
		<?php foreach ($category['entries'] as $entry ) :?>
			<div class="field">
				<h2><?php echo $entry->getLabel(); ?> - (<?php echo $entry->getIdVideo(); ?>)</h2>
				<div class="controls">
					(
					<a href="<?php echo $this->url(
				    array(
				        'controller'	=> 'megavideo',
				        'action'    	=> 'modify',
				        'id'			=> $entry->getId()
				    ),
				    'default',
				    true) ?>"><?php echo X_Env::_('megavideo_manage_modify');?></a>
				    <span class="separator">|</span>
				    <a href="<?php echo $this->url(
				    array(
				        'controller' => 'megavideo',
				        'action'     => 'delete',
				    	'type'		=>	'video',
				    	'id'			=> $entry->getId()
				    ),
				    'default',
				    true) ?>"><?php echo X_Env::_('megavideo_manage_delete');?></a>
				    )
				</div>
				<p><?php echo $entry->getDescription(); ?></p>
			</div>
		<?php endforeach; ?>
	</li>
	<?php endforeach;?>
</ul>
