<html>
<head>
	<title><?php echo X_Env::_('manage_title');?></title>
</head>
<body>
	<h1><?php echo X_Env::_('manage_title');?></h1>
	<h4>VLCShares <?php echo $this->version; ?></h4>
	<dl>
		<dt><?php echo X_Env::_('manage_config_path');?></dt>
		<dd><?php echo $this->configPath; ?></dd>
		<?php if ($this->pcstream_enabled ):?>
			<dt><?php echo X_Env::_('manage_pcstream_enabled');?></dt>
			<dd><a href="<?php echo $this->pcstream; ?>"><?php echo X_Env::_('manage_pcstream_link');?></a></dd>
		<?php endif;?>
		<dt><?php echo X_Env::_('manage_test');?></dt>
		<dd><a href="<?php echo $this->test; ?>"><?php echo X_Env::_('manage_test_link');?></a></dd>
		<?php foreach ($this->pluginsLinks as $link): ?>
			<dt><?php echo $link['actionName']; ?></dt>
			<dd><a href="<?php echo $link['actionLink']; ?>"><?php echo $link['actionDesc']; ?></a></dd>
		<?php endforeach; ?>
	</dl>
	<h4><?php echo X_Env::_('manage_plugin_configs'); ?></h4>
	<dl>
		<?php foreach ($this->pluginsConfs as $link): ?>
			<dt><?php echo $link['pluginName']; ?></dt>
			<dd><a href="<?php echo $link['pluginLink']; ?>"><?php echo $link['pluginDesc']; ?></a></dd>
		<?php endforeach; ?>
	</dl>
</body>
</html>