<!-- application/views/scripts/manage/index.phtml -->
<?php 

/* @var $v_messages X_Page_ItemList_Message */
$v_messages = $this->messages;

/* @var $v_news X_Page_ItemList_News */
$v_news = $this->news;

/* @var $v_actionLinks X_Page_ItemList_ActionLink */
$v_actionLinks = $this->actionLinks;

/* @var $v_manageLinks X_Page_ItemList_ManageLink */
$v_manageLinks = $this->manageLinks;

/* @var $v_statistics X_Page_ItemList_Statistics */
$v_statistics = $this->statistics;

$pluginTopNav = array();
$pluginApplications = array();
$pluginConfigs = array();

foreach ($v_manageLinks->getItems() as $manageLink) {
	/* @var $manageLink X_Page_Item_ManageLink */
	// only plugin with custom controller goes in topnav
		
	if ( $manageLink->isUrl() || $manageLink->getLinkController() == 'config' ) {
		$pluginConfigs[] = $manageLink;
	} else {
		$item = array(
			'label'		=>	$manageLink->getTitle(),
			'link'		=>	$manageLink->isUrl() ? $manageLink->getLink() : $this->url($manageLink->getLink(), $manageLink->getRoute(), $manageLink->isReset()),
			'icon'		=>	$manageLink->getIcon(),
			'title'		=>	$manageLink->getLabel(),
		);
		$pluginTopNav[] = $item;
		$pluginApplications[] = $manageLink;
	}
}

$topNav = array_merge($this->coreLinks, $pluginTopNav);

?>
<?php $this->headTitle()->prepend('Home'); ?>

<?php $this->placeholder('topNavigator')->captureStart(); ?>
	<ul class="columns same-height">
		<li class="fixed column topnav-button selected">
			<a href="<?php echo $this->url(); ?>">
				<img alt="<?php echo X_Env::_('p_altgui_topnav_dashboard'); ?>" src="<?php echo $this->baseUrl('/images/altgui/dashboard.png');?>" />
				<span><?php echo X_Env::_('p_altgui_topnav_dashboard'); ?></span>
			</a>
		</li>
		<?php foreach ($topNav as $topNavLink): ?>
			<li class="fixed column topnav-button">
				<a href="<?php echo $topNavLink['link'];?>">
					<?php if ( $topNavLink['icon'] == null ): ?>
						<img alt="<?php echo $topNavLink['title'] . ' - ' . $topNavLink['label']; ?>" src="<?php echo $this->baseUrl('/images/manage/plugin.png');?>" />
					<?php else: ?>
						<img alt="<?php echo $topNavLink['title'] . ' - ' . $topNavLink['label']; ?>" src="<?php echo $this->baseUrl($topNavLink['icon']);?>" />
					<?php endif; ?>
					<span><?php echo $topNavLink['label']; ?></span>
				</a>
			</li>
		<?php endforeach; ?>
		<li class="elastic column"></li>
	</ul>
<?php $this->placeholder('topNavigator')->captureEnd(); ?>
<?php $this->layout()->topNavigator = $this->placeholder('topNavigator'); ?>

<?php $this->placeholder('subNavigator')->captureStart(); ?>
	<ul class="columns same-height">
		<?php foreach ( $v_actionLinks->getItems() as $i => $link) :?>
			<?php /* @var $link X_Page_Item_ActionLink */ ?>
			<?php
				$_link = '';
				if ( $link->isUrl() ) {
					$_link = $link->getLink();
				} else {
					$_link = $this->url($link->getLink(), $link->getRoute(), $link->isReset());
				}
			?>
			<li class="fixed column subnav-button">
				<a href="<?php echo $_link; ?>">
					<!-- 
					<?php if ( $link->getIcon() != null ) : ?>
						<img class="icon" src="<?php echo $this->baseUrl($link->getIcon()); ?>" />
					<?php else: ?>
						<img class="icon" src="<?php echo $this->baseUrl('/images/right_arrow.png'); ?>" />								
					<?php endif; ?>
					-->
					<span><?php echo $link->getLabel(); ?></span>
				</a>
			</li>
		<?php endforeach; ?>
	</ul>
<?php $this->placeholder('subNavigator')->captureEnd(); ?>
<?php $this->layout()->subNavigator = $this->placeholder('subNavigator'); ?>

<?php $this->placeholder('breadcrumb')->captureStart(); ?>
	<ul>
		<li class="breadcrumb-button">
			<a href="<?php echo $this->url(); ?>">
				<span><?php echo X_Env::_('Home'); ?></span>
			</a>
		</li>
		<li class="breadcrumb-button">
			<a href="<?php echo $this->url(); ?>">
				<span><?php echo X_Env::_('p_altgui_topnav_dashboard'); ?></span>
			</a>
		</li>
	</ul>
<?php $this->placeholder('breadcrumb')->captureEnd(); ?>
<?php $this->layout()->breadcrumb = $this->placeholder('breadcrumb'); ?>

<?php $this->placeholder('status')->captureStart(); ?>
	<ul>
		<li>
			Logged in as <strong>THE ONE</strong>
		</li>
		<li>
			<a href="<?php echo $this->url(); ?>" class="button">
				<span><?php echo X_Env::_('p_altgui_profile'); ?></span>
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(); ?>" class="button red">
				<span><?php echo X_Env::_('p_altgui_logout'); ?></span>
			</a>
		</li>
		<!-- 
		<li>
			<a href="<?php echo $this->url(); ?>" class="button green">
				<span><?php echo X_Env::_('p_altgui_logout'); ?></span>
			</a>
		</li>
		<li>
			<a href="<?php echo $this->url(); ?>" class="button blue">
				<span><?php echo X_Env::_('p_altgui_logout'); ?></span>
			</a>
		</li>
		-->
	</ul>
<?php $this->placeholder('status')->captureEnd(); ?>
<?php $this->layout()->status = $this->placeholder('status'); ?>



<?php if ( count($v_messages->getItems()) ) :?>
	<ul class="messages">
		<?php foreach ($v_messages->getItems() as $i => $message ): ?>
			<?php /* @var $message X_Page_Item_Message */ ?>
			<li class="<?php echo $message->getType(); ?>">
				<img src="<?php echo @$this->baseUrl("/images/msg_{$message->getType()}.png");?>" alt="<?php echo $message->getType(); ?>" />
				<?php echo $message->getLabel(); ?>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>

<?php if ( $v_news != null && count($v_news->getItems()) ) :?>
<div class="columns on-2" id="news">
	<?php foreach ($v_news->getItems() as $i => $news) : ?>
		<?php /* @var $news X_Page_Item_News */ ?>
		<div class="elastic column full-height">
			<div class="container block titled">
				<div class="inner">
					<?php if ( $news->getTab() != '' ) : ?>
						<h1><?php echo $news->getTab(); ?></h1>
					<?php else: ?>
						<h1><?php echo $news->getLabel(); ?></h1>
					<?php endif; ?>
					<?php echo $news->getContent(); ?>
				</div>
			</div>
		</div>
	<?php endforeach; ?>
</div>
<?php endif; ?>

<div class="columns on-5">
	<div class="column span-3">
		<div class="container block titled" id="plugin-configs">
			<div class="inner">
				<h1><?php echo X_Env::_('p_altgui_plugins'); ?></h1>
				<?php if ( count($pluginApplications) ): ?>
					<h2><?php echo X_Env::_('p_altgui_pluginapplications'); ?></h2>
					<ul class="columns on-4 same-height">
						<?php foreach ($pluginApplications as $i => $link ): ?>
							<?php /* @var $link X_Page_Item_ManageLink */ ?>
							<li class="column config-button">
								<a class="container full-height" href="<?php echo $link->isUrl() ? $link->getLink() : $this->url($link->getLink(), $link->getRoute(), $link->isReset()); ?>">
									<?php if ( $link->getIcon() != null ):?>
										<img alt="<?php echo $link->getLabel(); ?>" class="thumb" src="<?php echo $this->baseUrl($link->getIcon());?>" />
									<?php else:?>
										<img alt="<?php echo $link->getLabel(); ?>" class="thumb" src="<?php echo $this->baseUrl('/images/manage/plugin.png');?>" />
									<?php endif;?>
									<?php echo $link->getTitle(); ?>
								</a>
							</li>
						<?php endforeach; ?>
					</ul>
				<?php endif; ?>
				<?php if ( count($pluginConfigs) ): ?>
					<h2><?php echo X_Env::_('p_altgui_pluginconfigs'); ?></h2>
					<ul class="columns on-4 same-height">
						<?php foreach ($pluginConfigs as $i => $link ): ?>
							<?php /* @var $link X_Page_Item_ManageLink */ ?>
							<li class="column config-button">
								<a class="container full-height" href="<?php echo $link->isUrl() ? $link->getLink() : $this->url($link->getLink(), $link->getRoute(), $link->isReset()); ?>">
									<?php if ( $link->getIcon() != null ):?>
										<img alt="<?php echo $link->getLabel(); ?>" class="thumb" src="<?php echo $this->baseUrl($link->getIcon());?>" />
									<?php else:?>
										<img alt="<?php echo $link->getLabel(); ?>" class="thumb" src="<?php echo $this->baseUrl('/images/manage/plugin.png');?>" />
									<?php endif;?>
									<?php echo $link->getTitle(); ?>
								</a>
							</li>
						<?php endforeach; ?>
					</ul>
				<?php endif; ?>
				
			</div>
		</div>
	</div>
	<div class="column span-2">
		<div class="container block titled" id="statistics">
			<div class="inner">
				<h1><?php echo X_Env::_('manage_statistics'); ?></h1>
				<?php foreach ($v_statistics->getItems() as $i => $statistic) : ?>
					<?php /* @var $statistic X_Page_Item_Statistic */ ?>
					<div class="inner-block titled">
						<div class="inner">
							<h1><?php echo $statistic->getTitle() ?></h1>
							<?php if ( $statistic->getLink() != null ) :?>
								<?php 
								$provider = $statistic->getLink();
								$params = clone $provider;
								unset($params['action']);
								unset($params['controller']);
								unset($params['module']);
								?>
								<?php echo $this->action(
										@$provider['action'],
										@$provider['controller'],
										@$provider['module'],
										@$params); ?>
							<?php else:?>
								<ul>
									<?php foreach ( @$statistic->getStats() as $i => $stat) :?>
										<li><?php echo $stat; ?></li>
									<?php endforeach; ?>
								</ul>
							<?php endif;?>
						</div>
					</div>
				<?php endforeach; ?>
			</div>
		</div>
	</div>
</div>

