<!-- application/views/scripts/manage/index.phtml -->
<?php 

/* @var $v_messages X_Page_ItemList_Message */
$v_messages = $this->messages;

/* @var $v_news X_Page_ItemList_News */
$v_news = $this->news;

/* @var $v_actionLinks X_Page_ItemList_ActionLink */
$v_actionLinks = $this->actionLinks;

/* @var $v_manageLinks X_Page_ItemList_ManageLink */
$v_manageLinks = $this->manageLinks;

/* @var $v_statistics X_Page_ItemList_Statistics */
$v_statistics = $this->statistics;

$pluginApplications = array();
$pluginConfigs = array();

foreach ($v_manageLinks->getItems() as $manageLink) {
	/* @var $manageLink X_Page_Item_ManageLink */
	// only plugin with custom controller goes in topnav
	if ( $manageLink->isUrl() || $manageLink->getLinkController() == 'config' ) {
		$pluginConfigs[] = $manageLink;
	} else {
		$pluginApplications[] = $manageLink;
	}
}

$this->headTitle()->prepend('Home');
$links = array();
foreach ( $v_actionLinks->getItems() as $link ) {
	$links[] = ((object) array(
		'label' => $link->getLabel(),
		'url'	=> $link->isUrl() ? $link->getLink() : $this->url($link->getLink(), $link->getRoute(), $link->isReset())
	));
}
$this->layout()->subNavigator = $this->xContextualMenu($links);

$breadcrumb = array(
	//array('label' => X_Env::_('Home'), 'url' => $this->url()  ),
	array('label' => X_Env::_('Dashboard'), /* 'url' => $this->url() */ ),
);
$this->layout()->breadcrumb = $this->xBreadcrumb($breadcrumb);
?>


<?php $this->placeholder('status')->captureStart(); ?>
	<ul>
		<li>
			Logged in as <strong>THE ONE</strong>
		</li>
		<li>
			<?php echo $this->xButton(
				X_Env::_('p_altgui_profile'), $this->url()
			)->setDimension(X_VlcShares_View_Helper_XButton::DIMENSION_SMALL); ?>
		</li>
		<li>
			<?php echo $this->xButton(
				X_Env::_('p_altgui_logout'),
				$this->url()
			)->setDimension(X_VlcShares_View_Helper_XButton::DIMENSION_SMALL)
			->setVariant(X_VlcShares_View_Helper_XButton::VARIANT_HIGHLIGHT); ?>
		</li>
	</ul>
<?php $this->placeholder('status')->captureEnd(); ?>
<?php $this->layout()->status = $this->placeholder('status'); ?>



<?php if ( count($v_messages->getItems()) ) :?>
	<ul class="messages">
		<?php foreach ($v_messages->getItems() as $i => $message ): ?>
			<?php /* @var $message X_Page_Item_Message */ ?>
			<li class="<?php echo $message->getType(); ?>">
				<img src="<?php echo @$this->baseUrl("/images/msg_{$message->getType()}.png");?>" alt="<?php echo $message->getType(); ?>" />
				<?php echo $message->getLabel(); ?>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>

<?php if ( $v_news != null && count($v_news->getItems()) ) :?>
<div class="columns on-2" id="news">
	<?php foreach ($v_news->getItems() as $i => $news) : ?>
		<?php /* @var $news X_Page_Item_News */ ?>
		<div class="elastic column full-height">
			<div class="container">
				<?php /* @var $xBlock X_VlcShares_View_Helper_XBlock */ ?>
				<?php $xBlock = $this->xBlock(); ?>
				<?php $xBlock->setTitle($news->getTab() != '' ? $news->getTab() : $news->getLabel() )->captureStart(); ?>
				 	<?php echo $news->getContent(); ?>
				 <?php $xBlock->captureEnd(true); ?>
			</div>
		</div>
	<?php endforeach; ?>
</div>
<?php endif; ?>

<div class="columns on-5">
	<div class="column span-3">
		<div class="container" id="plugin-configs">
			<?php $this->xBlock()->setTitle(X_Env::_('p_altgui_plugins'))->captureStart(); ?>
				<?php if ( count($pluginApplications) ): ?>
					<h2><?php echo X_Env::_('p_altgui_pluginapplications'); ?></h2>
					<ul class="columns on-4 same-height">
						<?php foreach ($pluginApplications as $i => $link ): ?>
							<?php /* @var $link X_Page_Item_ManageLink */ ?>
							<li class="column config-button">
								<a class="container full-height" href="<?php echo $link->isUrl() ? $link->getLink() : $this->url($link->getLink(), $link->getRoute(), $link->isReset()); ?>">
									<?php if ( $link->getIcon() != null ):?>
										<img alt="<?php echo $link->getLabel(); ?>" class="thumb" src="<?php echo $this->baseUrl($link->getIcon());?>" />
									<?php else:?>
										<img alt="<?php echo $link->getLabel(); ?>" class="thumb" src="<?php echo $this->baseUrl('/images/manage/plugin.png');?>" />
									<?php endif;?>
									<?php echo $link->getTitle(); ?>
								</a>
							</li>
						<?php endforeach; ?>
					</ul>
				<?php endif; ?>
				<?php if ( count($pluginConfigs) ): ?>
					<h2><?php echo X_Env::_('p_altgui_pluginconfigs'); ?></h2>
					<ul class="columns on-4 same-height">
						<?php foreach ($pluginConfigs as $i => $link ): ?>
							<?php /* @var $link X_Page_Item_ManageLink */ ?>
							<li class="column config-button">
								<a class="container full-height" href="<?php echo $link->isUrl() ? $link->getLink() : $this->url($link->getLink(), $link->getRoute(), $link->isReset()); ?>">
									<?php if ( $link->getIcon() != null ):?>
										<img alt="<?php echo $link->getLabel(); ?>" class="thumb" src="<?php echo $this->baseUrl($link->getIcon());?>" />
									<?php else:?>
										<img alt="<?php echo $link->getLabel(); ?>" class="thumb" src="<?php echo $this->baseUrl('/images/manage/plugin.png');?>" />
									<?php endif;?>
									<?php echo $link->getTitle(); ?>
								</a>
							</li>
						<?php endforeach; ?>
					</ul>
				<?php endif; ?>
			<?php $this->xBlock(false)->captureEnd(true); ?>
		</div>
	</div>
	<div class="column span-2">
		<div class="container" id="statistics">
			<?php $this->xBlock()->setTitle(X_Env::_('manage_statistics'))->captureStart(); ?>
				<?php foreach ($v_statistics->getItems() as $i => $statistic) : ?>
					<?php /* @var $statistic X_Page_Item_Statistic */ ?>
					<?php $this->xInnerBlock(false)->setTitle($statistic->getTitle())->captureStart(); ?>
						<?php if ( $statistic->getLink() != null ) :?>
							<?php 
							$provider = $statistic->getLink();
							$params = clone $provider;
							unset($params['action']);
							unset($params['controller']);
							unset($params['module']);
							?>
							<?php echo $this->action(
									@$provider['action'],
									@$provider['controller'],
									@$provider['module'],
									@$params); ?>
						<?php else:?>
							<ul>
								<?php foreach ( @$statistic->getStats() as $i => $stat) :?>
									<li><?php echo $stat; ?></li>
								<?php endforeach; ?>
							</ul>
						<?php endif;?>
					<?php $this->xInnerBlock(false)->captureEnd(true); ?>					
				<?php endforeach; ?>
			<?php $this->xBlock(false)->captureEnd(true); ?>
		</div>
	</div>
</div>

