<!-- application/views/scripts/profiles/index.phtml -->
<?php 

$menu = $this->guiElements()->menu()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::MENU_CONTEXTUAL));
$this->layout()->subNavigator =	$menu
	->addLinkRoute(X_Env::_('p_profiles_profile_new'), "profiles", "add");
	;
	
$breadcrumb = $this->guiElements()->menu()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::MENU_BREADCRUMB));
/* @var $breadcrumb X_VlcShares_Elements_Menu */
$this->layout()->breadcrumb = $breadcrumb
	->addLinkRoute(X_Env::_('Dashboard'), 'manage', 'index')
	->addLabel(X_Env::_('p_profiles_title'));

?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/profiles/style.css')); ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/profiles/index.js")); ?>
<?php $this->headTitle()->prepend(X_Env::_('p_profiles_title')); ?>


<?php if ( count($this->messages) ) :?>
<div class="span-24 last" id="manage-messages">
	<ul>
		<?php foreach ($this->messages as $i => $message ): ?>
			<?php if ( !is_array($message) ) $message = array('text' => $message, 'type' => 'warning'); ?>
			<li class="<?php echo @$message['type']?>">
				<img src="<?php echo @$this->baseUrl("/images/msg_{$message['type']}.png");?>" alt="<?php echo @$message['type']; ?>" />
				<?php echo $message['text']?>
			</li>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>

<div class="unit">
	<div class="container">
		<div class="box">
			<div class="header">
				<span class="title"><?php echo X_Env::_('p_profiles_tabletitle'); ?></span>
			</div>
			<div class="content">
				<table class="table" id="profiles-table">
					<tr class="header">
						<th><?php echo X_Env::_('p_profiles_header_label'); ?></th>
						<th><?php echo X_Env::_('p_profiles_header_arg'); ?></th>
						<th><?php echo X_Env::_('p_profiles_header_link'); ?></th>
						<th><?php echo X_Env::_('table_options'); ?></th>
					</tr>
					<?php foreach ( $this->profiles as $i => $profile): ?>
						<?php /* @var $profile Application_Model_Profile */?>
						<tr class="<?php echo $i % 2 ? 'alt' : ''?>" id="profileId-<?php echo $profile->getId(); ?>">
							<td><b><?php echo $profile->getLabel() ?></b></td>
							<td style="overflow: auto; max-width: 60%"><pre style="font-size: small;"><?php echo X_Env::codeFormat($profile->getArg()); ?></pre></td>
							<td><?php echo $profile->getLink() ?></td>
							<td>
								<ul class="inline-menu">
									<li class="ui-state-default">
										<a class="ui-icon ui-icon-pencil"
										title="<?php echo X_Env::_('edit')?>" 
										href="<?php echo $this->url(array(
											'controller' => 'profiles',
											'action' => 'edit',
											'id' => $profile->getId(),
										), 'default', true); ?>">R</a>
									</li>
									<li class="ui-state-default">
										<a class="ui-icon ui-icon-trash"
										title="<?php echo X_Env::_('remove')?>"
										href="<?php echo $this->url(array(
											'controller' => 'profiles',
											'action' => 'remove',
											'id' => $profile->getId(),
										), 'default', true); ?>">E</a>
									</li>
								</ul>								
							</td>
						</tr>
					<?php endforeach; ?>
				</table>
			</div>
		</div>
	</div>
</div>

