version=1
background=http://navix.turner3d.net/images/backgrounds/bkg_navix_bh_plain.jpg
logo=http://navix.turner3d.net/images/logos/logo.png
title=Vlc-shares - <?php echo $this->title ?> 
description=<?php echo $this->translate->_("title_description"); ?> 

type=playlist
name=<?php echo $this->bindex; ?> 
URL=<?php echo $this->bindex_url; ?>  

type=video 
name=<?php echo $this->name; ?> 
thumb=<?php echo $this->thumbnail ? $entry->thumbnail : 'http://navix.turner3d.net/images/logos/viewed.png'; ?> 
URL=<?php echo $this->url; ?> 
