<!-- application/views/scripts/plugin/index.phtml -->

<?php //$this->headScript()->appendFile($this->baseUrl("/js/plugin/index.js")); ?>
<?php $this->headScript()->captureStart(Zend_View_Helper_Placeholder_Container_Abstract::PREPEND); ?>
<?php $this->headScript()->captureEnd(); ?>
<?php $this->headTitle()->prepend(X_Env::_('plugin_uconfirm_title')); ?>

<div class="span-24 last" id="back-to-home">
	<div class="span-4 box back">
		<a href="<?php echo $this->url(array('controller' => 'manage', 'action' => 'index'), 'default', true); ?>"><?php echo X_Env::_('back_to_home'); ?></a>
	</div>
	<div class="span-18 box title last">
		<h4><?php echo X_Env::_('plugin_uconfirm_title'); ?></h4>
	</div>
</div>

<?php if ( count($this->messages) ) :?>
<div class="span-24 last" id="manage-messages">
	<ul>
		<?php foreach ($this->messages as $i => $message ): ?>
			<?php if ( !is_array($message) ) $message = array('text' => $message, 'type' => 'warning'); ?>
			<li class="<?php echo @$message['type']?>">
				<img src="<?php echo @$this->baseUrl("/images/msg_{$message['type']}.png");?>" alt="<?php echo @$message['type']; ?>" />
				<?php echo $message['text']?>
			</li>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>


<div class="span-24 last">
	<h2><?php echo X_Env::_('plugin_uconfirm_maintitle'); ?></h2>
	<p><?php echo X_Env::_('plugin_uconfirm_maindesc'); ?></p>
</div>

<div class="span-23 box">
	<h3><?php echo X_Env::_('plugin_uconfirm_confirmtitle'); ?></h3>
	<dl>
		<dt><?php echo X_Env::_('plugin_uconfirm_pluginlabel'); ?></dt>
		<dd><?php echo X_Env::_($this->plugin->getLabel()); ?>
		<dt><?php echo X_Env::_('plugin_uconfirm_plugindesc'); ?></dt>
		<dd><?php echo X_Env::_($this->plugin->getDescription()); ?></dd>
		<dt><?php echo X_Env::_('plugin_uconfirm_pluginkey'); ?></dt>
		<dd><?php echo $this->plugin->getKey(); ?></dd>
		<dt><?php echo X_Env::_('plugin_uconfirm_pluginversion'); ?></dt>
		<dd><?php echo $this->plugin->getVersion(); ?></dd>
	</dl>
	<form action="<?php echo $this->url(array('controller' => 'plugin', 'action' => 'uninstall'), 'default', true)?>" method="post">
		<?php echo $this->form->csrf; ?>
		<?php echo $this->form->key; ?>
		<?php echo $this->form->submit; ?> <?php echo X_Env::_('or')?> <a href="<?php echo $this->url(array('controller' => 'plugin', 'action' => 'index'), 'default', true);?>"><?php echo X_Env::_('abort');?></a>
	</form>
</div>
