
<div class="columns full-height">
	<div class="column">
		<div class="container vertical-center">
			<div class="block horizontal-center titled with-header red" id="error">
				<div class="inner">
					<h1>An error occurred</h1>
					<div class="header">
						<h3><?php echo $this->message; ?></h3>
					</div>
					<?php if (isset ($this->exception) ): ?>
					<h2>Error description</h2>
					<?php echo $this->exception->getMessage(); ?>
					<?php endif;?>
					<div class="inner-block titled">
						<div class="inner">
							<h1>Request parameters</h1>
							<pre style="overflow: auto;"><?php echo var_export($this->request->getParams(), true) ?></pre>
						</div>
					</div>
					<div class="inner-block titled">
						<div class="inner">
							<h1>Stack trace</h1>
							<pre style="overflow: auto;"><?php echo $this->exception->getTraceAsString() ?></pre>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
