<!-- application/views/scripts/filesystem/index.phtml -->
<?php 

$menu = $this->guiElements()->menu()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::MENU_CONTEXTUAL));
$this->layout()->subNavigator =	$menu
	->addLinkRoute(X_Env::_('p_filesystem_shares_new'), "filesystem", "add");
	;
	
$breadcrumb = $this->guiElements()->menu()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::MENU_BREADCRUMB));
/* @var $breadcrumb X_VlcShares_Elements_Menu */
$this->layout()->breadcrumb = $breadcrumb
	->addLinkRoute(X_Env::_('Dashboard'), 'manage', 'index')
	->addLabel(X_Env::_('p_filesystem_title'));

?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/filesystem/style.css')); ?>
<?php $this->headScript()->appendFile($this->baseUrl("/js/filesystem/index.js")); ?>
<?php $this->headTitle()->prepend(X_Env::_('p_filesystem_title')); ?>

<?php if ( count($this->messages) ) :?>
<div class="span-24 last" id="manage-messages">
	<ul>
		<?php foreach ($this->messages as $i => $message ): ?>
			<?php if ( !is_array($message) ) $message = array('text' => $message, 'type' => 'info'); ?>
			<li class="<?php echo @$message['type']?>">
				<img src="<?php echo @$this->baseUrl("/images/msg_{$message['type']}.png");?>" alt="<?php echo @$message['type']; ?>" />
				<?php echo $message['text']?>
			</li>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>

<div class="unit">
	<div class="container">
		<div class="box">
			<div class="header">
				<span class="title"><?php echo X_Env::_('p_filesystem_shares_title'); ?></span>
			</div>
			<div class="content">
				<table class="table" id="megavideo-categories">
					<tr class="header">
						<th><?php echo X_Env::_('p_filesystem_shares_tabletitle_label'); ?></th>
						<th><?php echo X_Env::_('p_filesystem_shares_tabletitle_path'); ?></th>
						<th width="100px"><?php echo X_Env::_('table_options'); ?></th>
					</tr>
					<?php foreach ( $this->shares as $i => $share): ?>
						<?php /* @var $share Application_Model_FileSystemShare */?>
						<tr class="<?php echo $i % 2 ? 'alt' : ''; ?>">
							<td><?php echo $share->getLabel(); ?></td>
							<td><?php echo $share->getPath(); ?></td>
							<td>
								<ul class="inline-menu">
									<li class="ui-state-default">
										<a class="ui-icon ui-icon-pencil"
										title="<?php echo X_Env::_('edit')?>" 
										href="<?php echo $this->url(array(
											'controller' => 'filesystem',
											'action' => 'edit',
											'id' => $share->getId(),
										), 'default', true); ?>">R</a>
									</li>
									<li class="ui-state-default">
										<a class="ui-icon ui-icon-trash"
										title="<?php echo X_Env::_('remove')?>"
										href="<?php echo $this->url(array(
											'controller' => 'filesystem',
											'action' => 'remove',
											'id' => $share->getId(),
										), 'default', true); ?>">E</a>
									</li>
								</ul>								
							</td>
						</tr>
					<?php endforeach; ?>
				</table>
			</div>
		</div>
	</div>
</div>
