<?php
/* @var $v_items X_Page_ItemList_PItem */
$v_items = $this->items; 
?>
<?php $this->layout()->disableLayout(); ?>
<ul class="items">
	<?php $preOption = true; ?>
	<?php foreach ($v_items->getItems() as $i => $item):?>
		<?php /* @var $item X_Page_Item_PItem */ ?>
		<?php if ( $item->getKey() == 'core-separator' ) { $preOption = false; continue; }?>
		<?php // skip items that aren't options ?>
		<?php if ( $preOption) { continue; }?>
		<li class="item mode <?php echo ($item->isHighlight() ? 'selected' : ''); ?>">
			<?php if ( $item->getIcon() != null ): ?>
				<img src="<?php echo $this->baseUrl($item->getIcon()); ?>"	alt="" width="32px" height="32px" />
			<?php endif; ?>
			<p class="title"><a href="<?php echo $item->isUrl() ? $item->getLink() : $this->url($item->getLink(), $item->getRoute(), $item->isReset()) ; ?>"><?php echo $item->getLabel(); ?></a></p>
			<?php if ( $item->getDescription() ): ?>
				<p class="date"><?php echo $item->getDescription(); ?></p>
			<?php endif; ?>
			<a href="<?php echo $item->isUrl() ? $item->getLink() : $this->url($item->getLink(), $item->getRoute(), $item->isReset()) ; ?>" class="button"></a>
			<div class="clear"></div>
		</li>
	<?php endforeach; ?>
</ul>