<!-- application/views/scripts/index/collections.mobile.phtml -->
<?php $this->headScript()->appendFile($this->baseUrl("/js/mobile/share.js")); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/mobile/share.css'), 'screen'); ?> 
<?php $this->headTitle()->prepend(X_Env::_('p_mobilerenderer_browse_share')); ?>

<div id="site_header">
	<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'collections'), 'default', true); ?>" id="usc_mobile">VLC Shares</a>
	<?php if ( $this->parentLocation !== false ) :?>
		<a href="<?php echo $this->url(array('l' => ($this->parentLocation == '' ? null : base64_encode($this->parentLocation))), 'default', false); ?>" id="app_icon">
			<img src="<?php echo $this->baseUrl('/images/mobile/back.png'); ?>" />
		</a>
	<?php else: ?>
		<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'collections'), 'default', true); ?>" id="app_icon">
			<img src="<?php echo $this->baseUrl('/images/mobile/back.png'); ?>" />
		</a>
	<?php endif; ?>
	<?php if ( $this->providerName != '' ) :?>
		<h1 class="site_title"><?php echo X_Env::_("p_{$this->providerName}_collectionindex"); ?></h1>
	<?php else: ?>
		<h1 class="site_title"><?php echo X_Env::_('p_mobilerenderer_noprovider_share'); ?></h1>
	<?php endif; ?>
</div>
<div id="wrapper">
	<h2><?php echo $this->location; ?></h2>
	<ul class="items">
		<!-- 
		<li class="item">
			<img src="http://uscnews.usc.edu/assets_c/2010/10/no smoking-thumb-65x65-27066.jpg"	alt="" />
			<p class="title"><a href="/news/story.php?id=42666">USC Hospitals Go Smoke Free Today</a></p>
			<p class="date">October 1, 2010</p>
			<a href="/news/story.php?id=42666" class="button"></a>
			<div class="clear"></div>
		</li>
		-->
		<?php foreach ($this->items as $i => $item):?>
			<li class="item">
				<?php if ( array_key_exists('icon', $item) ): ?>
					<img src="<?php echo $this->baseUrl($item['icon']); ?>" height="32px" width="32px" alt="" />
				<?php endif; ?>
				<p class="title"><a href="/news/story.php?id=42666"><?php echo $item['label']; ?></a></p>
				<?php if ( array_key_exists('desc', $item) ): ?>
					<p class="date"><?php echo $item['desc']; ?></p>
				<?php endif; ?>
				<a href="<?php echo $item['link']; ?>" class="button"></a>
				<div class="clear"></div>
			</li>
		<?php endforeach; ?>
	</ul>
</div>
<div id="footer"> 
	<ul> 
		<li><a id="feedback" href="http://code.google.com/p/vlc-shares/"><?php echo X_Env::_('p_mobilerenderer_footerproject')?></a></li> 
		<li><a id="uscHome" href="<?php echo $this->url(array('controller' => 'manage', 'action' => 'index' ), 'default', true);?>"><?php echo X_Env::_('p_mobilerenderer_footermanage'); ?></a></li> 
		<li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'collections' ), 'default', true);?>"><?php echo X_Env::_('p_mobilerenderer_footerindex')?></a></li> 
	</ul> 
</div>
