<!-- application/views/scripts/bookmarks/index.phtml -->
<?php $this->headScript()->appendFile($this->baseUrl("/js/bookmarks/script.js")); ?>
<?php //$this->headLink()->appendStylesheet($this->baseUrl('/css/onlinelibrary/style.css')); ?>
<?php 
$menu = $this->guiElements()->menu()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::MENU_CONTEXTUAL));
$this->layout()->subNavigator =	$menu
	->addLinkRoute(X_Env::_('p_bookmarks_actionaddpage'), "bookmarks", "add");
	
$breadcrumb = $this->guiElements()->menu()->setDecorator(X_VlcShares_Skins_Manager::i()->getDecorator(X_VlcShares_Skins_Manager::MENU_BREADCRUMB));
/* @var $breadcrumb X_VlcShares_Elements_Menu */
$this->layout()->breadcrumb = $breadcrumb
	->addLinkRoute(X_Env::_('Dashboard'), 'manage', 'index')
	->addLabel(X_Env::_('p_bookmarks_manage_title'));
	
	
$this->headTitle()->prepend(X_Env::_('p_bookmarks_manage_title'));

?>

<?php if ( count($this->messages) ) :?>
<div class="span-24 last" id="manage-messages">
	<ul>
		<?php foreach ($this->messages as $i => $message ): ?>
			<?php if ( !is_array($message) ) $message = array('text' => $message, 'type' => 'warning'); ?>
			<li class="<?php echo @$message['type']?>">
				<img src="<?php echo @$this->baseUrl("/images/msg_{$message['type']}.png");?>" alt="<?php echo @$message['type']; ?>" />
				<?php echo $message['text']?>
			</li>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>


<div class="unit columns on-2">
	<div class="elastic column">
		<div class="container">
			<div class="box">
				<div class="header">
					<span class="title"><?php echo X_Env::_('p_bookmarks_manage_title')?></span>
				</div>
				<div class="content">
					<table class="table" id="bookmarks-pages">
						<tr class="header">
							<th><?php echo X_Env::_('p_bookmarks_header_title')?></th>
							<th><?php echo X_Env::_('p_bookmarks_header_url')?></th>
							<th width="100px"><?php echo X_Env::_('table_options')?></th>
						</tr>
						<?php if ( count($this->bookmarks) ): ?>
							<?php foreach ($this->bookmarks as $i => $bookmark): ?>
							<?php /* @var $bookmark Application_Model_Bookmark */ ?>
								<tr class="<?php echo $i % 2 ? 'alt' : ''; ?>">
									<td><?php echo $bookmark->getTitle() ?></td>
									<td>
										<input type="text" disabled="disabled" value="<?php echo $bookmark->getUrl();?>" style="width: 100%" />
									</td>
									<td>
										<ul class="inline-menu">
											<li class="ui-state-default">
												<a class="ui-icon ui-icon-pencil onlinelibrary-category-rename" href="<?php echo $this->url(array(
													'controller' => 'bookmarks',
													'action' => 'edit',
													'id' => $bookmark->getId(),
												), 'default', true); ?>">R</a>
											</li>
											<li class="ui-state-default">
												<a class="ui-icon ui-icon-trash" href="<?php echo $this->url(array(
													'controller' => 'bookmarks',
													'action' => 'delete',
													'id' => $bookmark->getId(),
												), 'default', true); ?>">E</a>
											</li>
										</ul>
									</td>
								</tr>
							<?php endforeach; ?>
						<?php else: ?>
							<tr>
								<td colspan="3">
									<center>
										<i><?php echo X_Env::_('p_bookmarks_nobookmarks'); ?></i>
									</center>
								</td>
							</tr>
						<?php endif;?>
					</table>
					<?php if ( $this->pages > 1 ) : ?>
						<center>
							<ul class="paginator">
								<?php for ($i = 1; $i <= $this->pages; $i++ ): ?>
									<li>
										<?php if ( $i != $this->page ) : ?>
											<a href="<?php echo $this->url(array(
												'controller' => 'bookmarks',
												'action'	=> 'index',
												'page'	=> ($i == 1 ? null : $i)
											),'default', true)?>"><?php echo $i; ?></a>
										<?php else: ?>
											<?php echo $i; ?>
										<?php endif;?>
									</li>
								<?php endfor; ?>
							</ul>
						</center>
					<?php endif; ?>					
				</div>
			</div>
		</div>
	</div>
		<div class="fixed column" style="width: 400px">
			<div class="container">
				<?php if ( $this->bookmarkletsEnabled ) : ?>
					<div class="box" id="onlinelibrary-bookmarklets">
						<div class="header">
							<span class="title"><?php echo X_Env::_('p_onlinelibrary_manage_bookmarkletstitle')?></span>
						</div>
						<div class="content">
							<?php echo $this->action('index', 'bookmarklets'); ?>
						</div>
					</div>
				<?php endif; ?>
			</div>
		</div>
</div>
